# Generated by Django 5.1.3 on 2024-11-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='blabla',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
