# Generated by Django 5.1.3 on 2024-11-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_blabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='blabla',
        ),
    ]
